services:
  postgres:
    image: postgres:15
    container_name: capstone_postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: capstone

  node_app:
    build: .
    container_name: capstone_node_app
    ports:
      - "3000:3000"
    volumes:
      - logs:/app/logs
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - postgres

volumes:
  data:
  logs:
