version: '3.1'

services:
  postgres:
    image: postgres:15
    container_name: capstone_postgres
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: capstone
    networks:
      - newnetwork

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capstone_node_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - newnetwork

networks:
  newnetwork:
